replicaCount: 1



ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: artemis-dev.argocd.kadirozbey.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: artemis-dev-tls
      hosts:
        - artemis-dev.argocd.kadirozbey.net