replicaCount: 5

ingress:
  enabled: true
  className: nodejs
  annotations:
    nodejs.ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: nodejs-prod.argocd.kadirozbey.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: nodejs-prod-tls
      hosts:
        - nodejs-prod.argocd.kadirozbey.net