replicaCount: 5




ingress:
  enabled: true
  className: ""
  annotations: {}
    https://nginx-dev.projectxconsulting.net/
    https://nginx-qa.projectxconsulting.net/
    https://nginx-prod.projectxconsulting.net/
  hosts:
    - host: nginx-dev.argocd.kadirozbey.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
  - secretName: chart-example-tls
    hosts:
      - chart-example.local