replicaCount: 5

ingress:
  enabled: true
  className: "nginx"
  annotations:
    external-link-dev: "https://nginx-dev.projectxconsulting.net/"
    external-link-qa: "https://nginx-qa.projectxconsulting.net/"
    external-link-prod: "https://nginx-prod.projectxconsulting.net/"
  hosts:
    - host: nginx-dev.argocd.kadirozbey.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: nginx-dev-tls
      hosts:
        - nginx-dev.argocd.kadirozbey.net
