apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: nginx-prod
spec:
  project: default
  source:
    repoURL: https://github.com/ozbeyucel/ARGO-DEMO.git
    path: application
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../envs/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-prod
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
