apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-dev
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/ozbeyucel/ARGO-DEMO.git
    path: application
    targetRevision: HEAD
    helm:
      valueFiles:
        - .. nodejs/envs/dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-dev
 
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

        